name: Auto-labeling issue
on:
  workflow_call:
    inputs:
      issue-number:
        description: "Issue number"
        required: true
        type: number
      instructions:
        description: "Additional instructions for label selection"
        required: false
        type: string
        default: ""
      model:
        description: "Model to use"
        required: false
        type: string
        default: "o4-mini"
      provider:
        description: "Provider to use"
        required: false
        type: string
        default: "openai"
    secrets:
      personal-access-token:
        description: "Personal Access Token for PR creation"
        required: false
      openai-api-key:
        description: "OpenAI API key"
        required: false
      anthropic-api-key:
        description: "Anthropic API Key"
        required: false
      groq-api-key:
        description: "Groq API Key"
        required: false
      gemini-api-key:
        description: "Gemini API Key"
        required: false
      cohere-api-key:
        description: "Cohere API Key"
        required: false
      openrouter-api-key:
        description: "OpenRouter API Key"
        required: false
      deepseek-api-key:
        description: "Deepseek API Key"
        required: false

jobs:
  label_issue:
    permissions:
      issues: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Install LangChain CLI
        run: dotnet tool install --global langchain.cli --prerelease

      - name: Prepare prompt
        env:
          GITHUB_TOKEN: ${{ secrets.personal-access-token || secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.openai-api-key }}
          OPENROUTER_API_KEY: ${{ secrets.openrouter-api-key }}
          ANTHROPIC_API_KEY: ${{ secrets.anthropic-api-key }}
          COHERE_API_KEY: ${{ secrets.cohere-api-key }}
          GEMINI_API_KEY: ${{ secrets.gemini-api-key }}
          DEEPSEEK_API_KEY: ${{ secrets.deepseek-api-key }}
          GROQ_API_KEY: ${{ secrets.groq-api-key }}
        run: |
          ISSUE_DATA=$(gh issue view ${{ inputs.issue-number }})
          AVAILABLE_LABELS=$(gh label list)
          
          {
            echo "Return suitable labels(names) for issue with these data:"
            echo "----------------------------------------"
            echo "$ISSUE_DATA"
            echo "----------------------------------------"
            echo "Available labels:"
            echo "----------------------------------------"
            echo "$AVAILABLE_LABELS"
            echo "----------------------------------------"
            if [ -n "${{ inputs.instructions }}" ]; then
              echo "Additional instructions for label selection: ${{ inputs.instructions }}"
            fi
          } > .prompt.md
          
          echo "###################################################"
          echo "PROMPT"
          cat .prompt.md
          echo "###################################################"

          NEW_LABELS=$(langchain do --format lines --input-file .prompt.md --provider ${{ inputs.provider }} --model ${{ inputs.model }})

          echo "###################################################"
          echo "ANSWER"
          echo "$NEW_LABELS"
          echo "###################################################"
          
          ARGS=""
          # Process labels without using pipe to avoid subshell variable scope issues
          while read -r label; do
            if [ -n "$label" ]; then
              ARGS="$ARGS --add-label \"$label\""
            fi
          done <<< "$NEW_LABELS"
          
          # Get current issue body to preserve it
          # Note: When running `gh issue edit` in non-interactive mode (like in CI), 
          # it requires at least one field to edit flag. Since we only want to modify labels
          # without changing the body, we must fetch the current body and use --body-file
          # to effectively keep it unchanged.
          gh issue view ${{ inputs.issue-number }} --json body --jq .body > issue-body.txt
          
          COMMAND="gh issue edit ${{ inputs.issue-number }} --body-file issue-body.txt $ARGS"
          
          echo "Command to execute: $COMMAND"
          eval "$COMMAND"