name: Issue to PR using Devin
on:
  workflow_call:
    inputs:
      issue-number:
        description: "Issue number"
        required: true
        type: number
    secrets:
      devin-api-key:
        description: "Devin API key"
        required: true

jobs:
  create-devin-session:
    permissions:
      issues: write
      pull-requests: write
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Add eyes reaction to issue
        uses: actions/github-script@v7
        id: add_eyes_reaction
        with:
          script: |
            // Add "eyes" reaction to the issue
            await github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.issue-number }},
              content: 'eyes'
            });
            
            // Check if "completed" reaction exists and delete it
            const reactions = await github.rest.reactions.listForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.issue-number }}
            });
            
            for (const reaction of reactions.data) {
              if (reaction.content === 'rocket') {
                // Delete completed reaction
                await github.rest.reactions.deleteForIssue({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: ${{ inputs.issue-number }},
                  reaction_id: reaction.id
                });
              }
            }

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Devin session
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_data_raw=$(gh issue view ${{ inputs.issue-number }})
          issue_comments_raw=$(gh issue view ${{ inputs.issue-number }} --comments)

          # Prepare the prompt text
          # Note: We are creating a string that will be interpreted by the shell.
          # The actual heredoc will be formed and processed by the shell when the workflow runs.
          prompt_text_heredoc="Fix the issue #${{ inputs.issue-number }} in the repository ${{ github.repository }} and create a pull request. Use the following context: \n\nIssue data: \n\`\`\`\n$issue_data_raw\n\`\`\`\n\nIssue comments: \n\`\`\`\n$issue_comments_raw\n\`\`\`"

          # Use jq to create a valid JSON payload, escaping the prompt text appropriately
          # Pass the heredoc content as an argument to jq
          json_payload=$(jq -n --arg prompt "$prompt_text_heredoc" '{prompt: $prompt, idempotent: true}')

          # Make the API call with the JSON payload
          curl --request POST \\
            --url https://api.devin.ai/v1/sessions \\
            --header "Authorization: Bearer ${{ secrets.devin-api-key }}" \\
            --header 'Content-Type: application/json' \\
            --data "$json_payload"
